version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:5000"  # Backend
      - "3000:3000"  # Frontend
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - database

  database:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
